"""
Legacy ``MEDIAMOP_REFINER_*`` env names for failed-import cleanup (retired namespace).

These strings exist only in tests that prove the application ignores them in favor of
``MEDIAMOP_FAILED_IMPORT_*`` keys. Centralizing them avoids scattering retired identifiers.
"""

from __future__ import annotations

# Retired per-toggle keys (cleanup policy); must never be read by production loaders today.
LEGACY_REFINER_FAILED_IMPORT_CLEANUP_POLICY_ENV_KEYS: tuple[str, ...] = (
    "MEDIAMOP_REFINER_RADARR_CLEANUP_QUALITY",
    "MEDIAMOP_REFINER_RADARR_CLEANUP_UNMATCHED",
    "MEDIAMOP_REFINER_RADARR_CLEANUP_CORRUPT",
    "MEDIAMOP_REFINER_RADARR_CLEANUP_DOWNLOAD_FAILED",
    "MEDIAMOP_REFINER_RADARR_CLEANUP_IMPORT_FAILED",
    "MEDIAMOP_REFINER_SONARR_CLEANUP_QUALITY",
    "MEDIAMOP_REFINER_SONARR_CLEANUP_UNMATCHED",
    "MEDIAMOP_REFINER_SONARR_CLEANUP_CORRUPT",
    "MEDIAMOP_REFINER_SONARR_CLEANUP_DOWNLOAD_FAILED",
    "MEDIAMOP_REFINER_SONARR_CLEANUP_IMPORT_FAILED",
)

LEGACY_REFINER_RADARR_CLEANUP_CORRUPT = "MEDIAMOP_REFINER_RADARR_CLEANUP_CORRUPT"
LEGACY_REFINER_SONARR_CLEANUP_IMPORT_FAILED = "MEDIAMOP_REFINER_SONARR_CLEANUP_IMPORT_FAILED"

# Retired schedule keys for Radarr drive; production reads ``MEDIAMOP_FAILED_IMPORT_*`` only.
LEGACY_REFINER_RADARR_DRIVE_SCHEDULE_ENABLED = "MEDIAMOP_REFINER_RADARR_CLEANUP_DRIVE_SCHEDULE_ENABLED"
LEGACY_REFINER_RADARR_DRIVE_SCHEDULE_INTERVAL_SECONDS = "MEDIAMOP_REFINER_RADARR_CLEANUP_DRIVE_SCHEDULE_INTERVAL_SECONDS"
