import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'quickstart',
    {
      type: 'category',
      label: 'Deployment',
      items: [{type: 'autogenerated', dirName: 'deployment'}],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
  ],
  apiSidebar: [
    {type: 'autogenerated', dirName: 'api'},
  ],
};

export default sidebars;
