"""Dump the SQLite schema that the Python backend's Alembic head creates.

The .NET server (``apps/server``) must create exactly this schema. Its parity test
(``Weir.Infrastructure.Tests``) loads the reference written here into a fresh SQLite file
and compares it, structure by structure, with the schema the .NET migrations create.

Run with the backend's virtualenv so Alembic and the ``weir`` package import:

    apps/backend/.venv/Scripts/python.exe scripts/dump-alembic-schema.py          # write
    apps/backend/.venv/Scripts/python.exe scripts/dump-alembic-schema.py --check  # compare only

The output is normalized: one statement per ``sqlite_master`` object (tables, then indexes,
triggers and views, each sorted by name), LF line endings, and a header naming the head
revision, followed by the rows Alembic head seeds (singleton settings, the default libraries
and rule sets, ``alembic_version``) as ``INSERT`` statements ordered by table and rowid. Seed
timestamps are the migration's wall-clock time, so they are written as ``CURRENT_TIMESTAMP``.
"""

from __future__ import annotations

import argparse
import os
import re
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = REPO_ROOT / "apps" / "backend"
DEFAULT_OUTPUT = REPO_ROOT / "apps" / "server" / "tests" / "Weir.Infrastructure.Tests" / "schema" / "alembic-head.sql"
_TYPE_ORDER = {"table": 0, "index": 1, "trigger": 2, "view": 3}
_SEED_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$")


def _sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int | float):
        return repr(value)
    if isinstance(value, bytes):
        return "X'" + value.hex().upper() + "'"
    text = str(value)
    if _SEED_TIMESTAMP.match(text):
        return "CURRENT_TIMESTAMP"
    return "'" + text.replace("'", "''") + "'"


def _run_alembic_upgrade(home: Path) -> Path:
    db_path = home / "data" / "weir.sqlite3"
    env = {key: value for key, value in os.environ.items() if not key.startswith("WEIR_")}
    env["WEIR_HOME"] = str(home)
    # Explicit, so a developer's apps/backend/.env cannot point Alembic somewhere else
    # (python-dotenv never overrides a variable that is already set).
    env["WEIR_DB_PATH"] = str(db_path)
    env["WEIR_BACKUP_DIR"] = str(home / "backups")
    env["WEIR_LOG_DIR"] = str(home / "logs")
    env["WEIR_TEMP_DIR"] = str(home / "temp")
    env["PYTHONPATH"] = str(BACKEND_ROOT / "src")
    subprocess.run(  # noqa: S603 - fixed argv, no shell
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=BACKEND_ROOT,
        env=env,
        check=True,
    )
    return db_path


def _normalize_sql(sql: str) -> str:
    lines = [line.rstrip() for line in sql.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    return "\n".join(lines).strip()


def build_reference(db_path: Path) -> str:
    conn = sqlite3.connect(db_path)
    try:
        objects = conn.execute(
            "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'"
        ).fetchall()
        revisions = [row[0] for row in conn.execute("SELECT version_num FROM alembic_version")]
        if len(revisions) != 1:
            raise SystemExit(f"Expected exactly one alembic_version row, found {revisions!r}.")
        inserts: list[str] = []
        tables = [
            row[0]
            for row in conn.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        ]
        for table in tables:
            columns = [row[1] for row in conn.execute(f'PRAGMA table_info("{table}")')]
            column_list = ", ".join(f'"{name}"' for name in columns)
            select = f'SELECT {column_list} FROM "{table}" ORDER BY rowid'  # noqa: S608 - names from sqlite_master
            for values in conn.execute(select):
                rendered = ", ".join(_sql_literal(value) for value in values)
                inserts.append(f'INSERT INTO "{table}" ({column_list}) VALUES ({rendered});')
    finally:
        conn.close()

    objects.sort(key=lambda row: (_TYPE_ORDER.get(row[0], 9), row[1]))
    parts = [
        "-- Weir SQLite schema at Alembic head. Generated by scripts/dump-alembic-schema.py; do not edit.",
        f"-- alembic_revision: {revisions[0]}",
        "",
    ]
    for _type, _name, sql in objects:
        parts.append(_normalize_sql(sql) + ";")
        parts.append("")
    parts.append("-- Rows seeded by Alembic head.")
    parts.extend(inserts)
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the checked-in reference is out of date")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory(prefix="weir-alembic-schema-") as tmp:
        reference = build_reference(_run_alembic_upgrade(Path(tmp)))

    output: Path = args.output
    if args.check:
        current = output.read_text(encoding="utf-8").replace("\r\n", "\n") if output.is_file() else ""
        if current != reference:
            print(f"{output} is out of date; run scripts/dump-alembic-schema.py to regenerate it.", file=sys.stderr)
            return 1
        print(f"{output} matches Alembic head.")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(reference, encoding="utf-8", newline="\n")
    print(f"Wrote {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
